//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unlock
    {
        public int ID { get; set; }
		public string Idea_Name { get; set; }
public string Owner { get; set; }
public string Problem { get; set; }
public string Benefit { get; set; }

    }
}
